services:
  postgres:
    container_name: postgres_db
    image: postgres:15.8
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: